### PR TITLE
add language selector

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@SteveBarnett the selector on ebola needs a bit more styling

**Comment by SteveBarnett** [comment]
@miltontony Quick review, please?

**Comment by miltontony** [comment]
@SteveBarnett slight problem on the selector page when the nav is hidden
screenshot from 2015-02-04 10 04 54

**Comment by SteveBarnett** [comment]
@miltontony Fixed!

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
